2023-08-25 04:41:09,466:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-08-25 04:41:09,466:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-08-25 04:41:09,466:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-08-25 04:41:09,466:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-08-25 04:45:39,897:INFO:PyCaret ClassificationExperiment
2023-08-25 04:45:39,898:INFO:Logging name: clf-default-name
2023-08-25 04:45:39,898:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-08-25 04:45:39,898:INFO:version 3.0.4
2023-08-25 04:45:39,898:INFO:Initializing setup()
2023-08-25 04:45:39,898:INFO:self.USI: 0d1b
2023-08-25 04:45:39,898:INFO:self._variable_keys: {'y_test', 'y', 'X', 'X_test', 'gpu_n_jobs_param', 'html_param', 'log_plots_param', 'fold_groups_param', 'seed', 'logging_param', 'fold_generator', 'exp_id', 'exp_name_log', 'pipeline', 'USI', 'target_param', '_ml_usecase', 'fold_shuffle_param', 'gpu_param', 'idx', '_available_plots', 'n_jobs_param', 'X_train', 'fix_imbalance', 'data', 'y_train', 'is_multiclass', 'memory'}
2023-08-25 04:45:39,898:INFO:Checking environment
2023-08-25 04:45:39,898:INFO:python_version: 3.9.12
2023-08-25 04:45:39,898:INFO:python_build: ('main', 'Apr  5 2022 01:53:17')
2023-08-25 04:45:39,898:INFO:machine: x86_64
2023-08-25 04:45:39,898:INFO:platform: macOS-10.16-x86_64-i386-64bit
2023-08-25 04:45:39,898:INFO:Memory: svmem(total=8589934592, available=2257408000, percent=73.7, used=4655112192, free=55066624, active=2203824128, inactive=2200186880, wired=2451288064)
2023-08-25 04:45:39,898:INFO:Physical Core: 2
2023-08-25 04:45:39,898:INFO:Logical Core: 4
2023-08-25 04:45:39,898:INFO:Checking libraries
2023-08-25 04:45:39,898:INFO:System:
2023-08-25 04:45:39,898:INFO:    python: 3.9.12 (main, Apr  5 2022, 01:53:17)  [Clang 12.0.0 ]
2023-08-25 04:45:39,898:INFO:executable: /Users/kendallherron/opt/anaconda3/bin/python
2023-08-25 04:45:39,899:INFO:   machine: macOS-10.16-x86_64-i386-64bit
2023-08-25 04:45:39,899:INFO:PyCaret required dependencies:
2023-08-25 05:12:31,805:INFO:PyCaret ClassificationExperiment
2023-08-25 05:12:31,809:INFO:Logging name: clf-default-name
2023-08-25 05:12:31,810:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-08-25 05:12:31,810:INFO:version 3.0.4
2023-08-25 05:12:31,810:INFO:Initializing setup()
2023-08-25 05:12:31,810:INFO:self.USI: 7359
2023-08-25 05:12:31,813:INFO:self._variable_keys: {'y_test', 'y', 'X', 'X_test', 'gpu_n_jobs_param', 'html_param', 'log_plots_param', 'fold_groups_param', 'seed', 'logging_param', 'fold_generator', 'exp_id', 'exp_name_log', 'pipeline', 'USI', 'target_param', '_ml_usecase', 'fold_shuffle_param', 'gpu_param', 'idx', '_available_plots', 'n_jobs_param', 'X_train', 'fix_imbalance', 'data', 'y_train', 'is_multiclass', 'memory'}
2023-08-25 05:12:31,813:INFO:Checking environment
2023-08-25 05:12:31,814:INFO:python_version: 3.9.12
2023-08-25 05:12:31,814:INFO:python_build: ('main', 'Apr  5 2022 01:53:17')
2023-08-25 05:12:31,814:INFO:machine: x86_64
2023-08-25 05:12:31,814:INFO:platform: macOS-10.16-x86_64-i386-64bit
2023-08-25 05:12:31,819:INFO:Memory: svmem(total=8589934592, available=2973614080, percent=65.4, used=4435148800, free=476102656, active=1920020480, inactive=2295660544, wired=2515128320)
2023-08-25 05:12:31,819:INFO:Physical Core: 2
2023-08-25 05:12:31,819:INFO:Logical Core: 4
2023-08-25 05:12:31,819:INFO:Checking libraries
2023-08-25 05:12:31,820:INFO:System:
2023-08-25 05:12:31,821:INFO:    python: 3.9.12 (main, Apr  5 2022, 01:53:17)  [Clang 12.0.0 ]
2023-08-25 05:12:31,821:INFO:executable: /Users/kendallherron/opt/anaconda3/bin/python
2023-08-25 05:12:31,821:INFO:   machine: macOS-10.16-x86_64-i386-64bit
2023-08-25 05:12:31,821:INFO:PyCaret required dependencies:
2023-08-25 05:12:31,892:INFO:                 pip: 21.2.4
2023-08-25 05:12:31,892:INFO:          setuptools: 61.2.0
2023-08-25 05:12:31,892:INFO:             pycaret: 3.0.4
2023-08-25 05:12:31,892:INFO:             IPython: 8.2.0
2023-08-25 05:12:31,892:INFO:          ipywidgets: 7.6.5
2023-08-25 05:12:31,892:INFO:                tqdm: 4.64.0
2023-08-25 05:12:31,893:INFO:               numpy: 1.21.5
2023-08-25 05:12:31,893:INFO:              pandas: 1.4.2
2023-08-25 05:12:31,893:INFO:              jinja2: 2.11.3
2023-08-25 05:12:31,893:INFO:               scipy: 1.7.3
2023-08-25 05:12:31,893:INFO:              joblib: 1.3.2
2023-08-25 05:12:31,893:INFO:             sklearn: 1.0.2
2023-08-25 05:12:31,893:INFO:                pyod: 1.1.0
2023-08-25 05:12:31,893:INFO:            imblearn: 0.11.0
2023-08-25 05:12:31,893:INFO:   category_encoders: 2.6.2
2023-08-25 05:12:31,893:INFO:            lightgbm: Not installed
2023-08-25 05:12:31,893:INFO:               numba: 0.55.1
2023-08-25 05:12:31,893:INFO:            requests: 2.27.1
2023-08-25 05:12:31,893:INFO:          matplotlib: 3.5.1
2023-08-25 05:12:31,893:INFO:          scikitplot: 0.3.7
2023-08-25 05:12:31,893:INFO:         yellowbrick: 1.5
2023-08-25 05:12:31,893:INFO:              plotly: 5.6.0
2023-08-25 05:12:31,893:INFO:    plotly-resampler: Not installed
2023-08-25 05:12:31,893:INFO:             kaleido: 0.2.1
2023-08-25 05:12:31,893:INFO:           schemdraw: 0.15
2023-08-25 05:12:31,893:INFO:         statsmodels: 0.13.2
2023-08-25 05:12:31,893:INFO:              sktime: 0.22.0
2023-08-25 05:12:31,894:INFO:               tbats: 1.1.3
2023-08-25 05:12:31,894:INFO:            pmdarima: 2.0.3
2023-08-25 05:12:31,894:INFO:              psutil: 5.9.5
2023-08-25 05:12:31,894:INFO:          markupsafe: 2.0.1
2023-08-25 05:12:31,894:INFO:             pickle5: Not installed
2023-08-25 05:12:31,894:INFO:         cloudpickle: 2.0.0
2023-08-25 05:12:31,894:INFO:         deprecation: 2.1.0
2023-08-25 05:12:31,894:INFO:              xxhash: 3.3.0
2023-08-25 05:12:31,894:INFO:           wurlitzer: 3.0.2
2023-08-25 05:12:31,894:INFO:PyCaret optional dependencies:
2023-08-25 05:12:42,061:INFO:                shap: Not installed
2023-08-25 05:12:42,061:INFO:           interpret: Not installed
2023-08-25 05:12:42,061:INFO:                umap: 0.5.3
2023-08-25 05:12:42,061:INFO:    pandas_profiling: 3.6.2
2023-08-25 05:12:42,061:INFO:  explainerdashboard: Not installed
2023-08-25 05:12:42,061:INFO:             autoviz: Not installed
2023-08-25 05:12:42,061:INFO:           fairlearn: Not installed
2023-08-25 05:12:42,061:INFO:          deepchecks: Not installed
2023-08-25 05:12:42,061:INFO:             xgboost: Not installed
2023-08-25 05:12:42,061:INFO:            catboost: Not installed
2023-08-25 05:12:42,061:INFO:              kmodes: Not installed
2023-08-25 05:12:42,061:INFO:             mlxtend: Not installed
2023-08-25 05:12:42,061:INFO:       statsforecast: Not installed
2023-08-25 05:12:42,061:INFO:        tune_sklearn: Not installed
2023-08-25 05:12:42,061:INFO:                 ray: Not installed
2023-08-25 05:12:42,062:INFO:            hyperopt: Not installed
2023-08-25 05:12:42,062:INFO:              optuna: Not installed
2023-08-25 05:12:42,062:INFO:               skopt: Not installed
2023-08-25 05:12:42,062:INFO:              mlflow: Not installed
2023-08-25 05:12:42,062:INFO:              gradio: Not installed
2023-08-25 05:12:42,062:INFO:             fastapi: Not installed
2023-08-25 05:12:42,062:INFO:             uvicorn: Not installed
2023-08-25 05:12:42,062:INFO:              m2cgen: Not installed
2023-08-25 05:12:42,062:INFO:           evidently: Not installed
2023-08-25 05:12:42,062:INFO:               fugue: Not installed
2023-08-25 05:12:42,062:INFO:           streamlit: Not installed
2023-08-25 05:12:42,062:INFO:             prophet: Not installed
2023-08-25 05:12:42,062:INFO:None
2023-08-25 05:12:42,062:INFO:Set up data.
2023-08-25 05:12:42,098:INFO:Set up train/test split.
2023-08-25 05:12:42,130:INFO:Set up index.
2023-08-25 05:12:42,132:INFO:Set up folding strategy.
2023-08-25 05:12:42,133:INFO:Assigning column types.
2023-08-25 05:12:42,139:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-08-25 05:12:42,190:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-08-25 05:12:42,197:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-25 05:12:42,249:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:13:50,228:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-08-25 05:13:50,229:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-08-25 05:13:50,229:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-08-25 05:13:50,229:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-08-25 05:14:45,417:INFO:PyCaret ClassificationExperiment
2023-08-25 05:14:45,418:INFO:Logging name: clf-default-name
2023-08-25 05:14:45,418:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-08-25 05:14:45,418:INFO:version 3.0.4
2023-08-25 05:14:45,418:INFO:Initializing setup()
2023-08-25 05:14:45,418:INFO:self.USI: bdb8
2023-08-25 05:14:45,418:INFO:self._variable_keys: {'y_train', '_available_plots', 'idx', 'exp_id', 'fold_generator', 'exp_name_log', 'seed', 'USI', '_ml_usecase', 'html_param', 'data', 'log_plots_param', 'pipeline', 'fold_groups_param', 'n_jobs_param', 'is_multiclass', 'logging_param', 'X_train', 'gpu_param', 'gpu_n_jobs_param', 'X', 'X_test', 'y', 'fix_imbalance', 'target_param', 'y_test', 'memory', 'fold_shuffle_param'}
2023-08-25 05:14:45,418:INFO:Checking environment
2023-08-25 05:14:45,418:INFO:python_version: 3.9.12
2023-08-25 05:14:45,419:INFO:python_build: ('main', 'Apr  5 2022 01:53:17')
2023-08-25 05:14:45,419:INFO:machine: x86_64
2023-08-25 05:14:45,419:INFO:platform: macOS-10.16-x86_64-i386-64bit
2023-08-25 05:14:45,419:INFO:Memory: svmem(total=8589934592, available=2651287552, percent=69.1, used=4656373760, free=559874048, active=1952780288, inactive=2044710912, wired=2703593472)
2023-08-25 05:14:45,419:INFO:Physical Core: 2
2023-08-25 05:14:45,419:INFO:Logical Core: 4
2023-08-25 05:14:45,420:INFO:Checking libraries
2023-08-25 05:14:45,420:INFO:System:
2023-08-25 05:14:45,420:INFO:    python: 3.9.12 (main, Apr  5 2022, 01:53:17)  [Clang 12.0.0 ]
2023-08-25 05:14:45,420:INFO:executable: /Users/kendallherron/opt/anaconda3/bin/python
2023-08-25 05:14:45,420:INFO:   machine: macOS-10.16-x86_64-i386-64bit
2023-08-25 05:14:45,420:INFO:PyCaret required dependencies:
2023-08-25 05:14:45,426:INFO:                 pip: 21.2.4
2023-08-25 05:14:45,426:INFO:          setuptools: 61.2.0
2023-08-25 05:14:45,426:INFO:             pycaret: 3.0.4
2023-08-25 05:14:45,426:INFO:             IPython: 8.2.0
2023-08-25 05:14:45,427:INFO:          ipywidgets: 7.6.5
2023-08-25 05:14:45,427:INFO:                tqdm: 4.64.0
2023-08-25 05:14:45,427:INFO:               numpy: 1.21.5
2023-08-25 05:14:45,427:INFO:              pandas: 1.4.2
2023-08-25 05:14:45,427:INFO:              jinja2: 2.11.3
2023-08-25 05:14:45,427:INFO:               scipy: 1.7.3
2023-08-25 05:14:45,427:INFO:              joblib: 1.3.2
2023-08-25 05:14:45,427:INFO:             sklearn: 1.0.2
2023-08-25 05:14:45,427:INFO:                pyod: 1.1.0
2023-08-25 05:14:45,427:INFO:            imblearn: 0.11.0
2023-08-25 05:14:45,427:INFO:   category_encoders: 2.6.2
2023-08-25 05:14:45,427:INFO:            lightgbm: 3.3.2
2023-08-25 05:14:45,427:INFO:               numba: 0.55.1
2023-08-25 05:14:45,427:INFO:            requests: 2.27.1
2023-08-25 05:14:45,427:INFO:          matplotlib: 3.5.1
2023-08-25 05:14:45,427:INFO:          scikitplot: 0.3.7
2023-08-25 05:14:45,427:INFO:         yellowbrick: 1.5
2023-08-25 05:14:45,427:INFO:              plotly: 5.6.0
2023-08-25 05:14:45,428:INFO:    plotly-resampler: Not installed
2023-08-25 05:14:45,428:INFO:             kaleido: 0.2.1
2023-08-25 05:14:45,428:INFO:           schemdraw: 0.15
2023-08-25 05:14:45,428:INFO:         statsmodels: 0.13.2
2023-08-25 05:14:45,428:INFO:              sktime: 0.21.1
2023-08-25 05:14:45,428:INFO:               tbats: 1.1.3
2023-08-25 05:14:45,428:INFO:            pmdarima: 1.8.4
2023-08-25 05:14:45,428:INFO:              psutil: 5.9.5
2023-08-25 05:14:45,428:INFO:          markupsafe: 2.0.1
2023-08-25 05:14:45,428:INFO:             pickle5: Not installed
2023-08-25 05:14:45,428:INFO:         cloudpickle: 2.0.0
2023-08-25 05:14:45,428:INFO:         deprecation: 2.1.0
2023-08-25 05:14:45,428:INFO:              xxhash: 3.3.0
2023-08-25 05:14:45,428:INFO:           wurlitzer: 3.0.2
2023-08-25 05:14:45,428:INFO:PyCaret optional dependencies:
2023-08-25 05:14:45,472:INFO:                shap: Not installed
2023-08-25 05:14:45,472:INFO:           interpret: Not installed
2023-08-25 05:14:45,472:INFO:                umap: 0.5.3
2023-08-25 05:14:45,472:INFO:    pandas_profiling: 3.6.2
2023-08-25 05:14:45,472:INFO:  explainerdashboard: Not installed
2023-08-25 05:14:45,472:INFO:             autoviz: Not installed
2023-08-25 05:14:45,472:INFO:           fairlearn: Not installed
2023-08-25 05:14:45,472:INFO:          deepchecks: Not installed
2023-08-25 05:14:45,472:INFO:             xgboost: Not installed
2023-08-25 05:14:45,472:INFO:            catboost: Not installed
2023-08-25 05:14:45,472:INFO:              kmodes: Not installed
2023-08-25 05:14:45,472:INFO:             mlxtend: Not installed
2023-08-25 05:14:45,472:INFO:       statsforecast: Not installed
2023-08-25 05:14:45,473:INFO:        tune_sklearn: Not installed
2023-08-25 05:14:45,473:INFO:                 ray: Not installed
2023-08-25 05:14:45,473:INFO:            hyperopt: Not installed
2023-08-25 05:14:45,473:INFO:              optuna: Not installed
2023-08-25 05:14:45,473:INFO:               skopt: Not installed
2023-08-25 05:14:45,473:INFO:              mlflow: Not installed
2023-08-25 05:14:45,473:INFO:              gradio: Not installed
2023-08-25 05:14:45,473:INFO:             fastapi: Not installed
2023-08-25 05:14:45,473:INFO:             uvicorn: Not installed
2023-08-25 05:14:45,473:INFO:              m2cgen: Not installed
2023-08-25 05:14:45,473:INFO:           evidently: Not installed
2023-08-25 05:14:45,473:INFO:               fugue: Not installed
2023-08-25 05:14:45,473:INFO:           streamlit: Not installed
2023-08-25 05:14:45,473:INFO:             prophet: Not installed
2023-08-25 05:14:45,473:INFO:None
2023-08-25 05:14:45,473:INFO:Set up data.
2023-08-25 05:14:45,510:INFO:Set up train/test split.
2023-08-25 05:14:45,541:INFO:Set up index.
2023-08-25 05:14:45,543:INFO:Set up folding strategy.
2023-08-25 05:14:45,543:INFO:Assigning column types.
2023-08-25 05:14:45,552:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-08-25 05:14:45,617:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-08-25 05:14:45,623:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-25 05:14:45,688:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:14:46,161:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:14:46,242:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-08-25 05:14:46,243:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-25 05:14:46,296:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:14:46,297:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:14:46,298:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-08-25 05:14:46,371:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-25 05:14:46,420:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:14:46,420:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:14:46,499:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-25 05:14:46,542:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:14:46,542:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:14:46,543:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-08-25 05:14:46,677:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:14:46,678:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:14:46,812:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:14:46,812:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:14:46,816:INFO:Preparing preprocessing pipeline...
2023-08-25 05:14:46,821:INFO:Set up simple imputation.
2023-08-25 05:14:46,823:INFO:Set up column name cleaning.
2023-08-25 05:14:46,886:INFO:Finished creating preprocessing pipeline.
2023-08-25 05:14:46,896:INFO:Pipeline: Pipeline(memory=FastMemory(location=/var/folders/m3/xf6gvy7n3qdbcwzd5vjb0b7r0000gn/T/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['AcountNumber', 'CVV',
                                             'CustomerAge', 'Amount',
                                             'AverageIncomeExpendicture',
                                             'Gender_Female', 'Gender_Male',
                                             'MaritalStatus_Divorced',
                                             'MaritalStatus_Married',
                                             'MaritalStatus_Single',
                                             'MaritalStatus...
                                                              verbose=0))),
                ('categorical_imputer',
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose=0))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+')))],
         verbose=False)
2023-08-25 05:14:46,896:INFO:Creating final display dataframe.
2023-08-25 05:14:47,110:INFO:Setup _display_container:                     Description             Value
0                    Session id              1754
1                        Target           Outcome
2                   Target type            Binary
3           Original data shape       (37097, 27)
4        Transformed data shape       (37097, 27)
5   Transformed train set shape       (25967, 27)
6    Transformed test set shape       (11130, 27)
7              Numeric features                26
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                10
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              bdb8
2023-08-25 05:14:47,240:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:14:47,240:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:14:47,354:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:14:47,355:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:14:47,357:INFO:setup() successfully completed in 1.95s...............
2023-08-25 05:16:44,389:INFO:Initializing compare_models()
2023-08-25 05:16:44,390:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f8c64fd1250>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x7f8c64fd1250>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-08-25 05:16:44,390:INFO:Checking exceptions
2023-08-25 05:16:44,409:INFO:Preparing display monitor
2023-08-25 05:16:44,504:INFO:Initializing Logistic Regression
2023-08-25 05:16:44,504:INFO:Total runtime is 8.070468902587891e-06 minutes
2023-08-25 05:16:44,510:INFO:SubProcess create_model() called ==================================
2023-08-25 05:16:44,511:INFO:Initializing create_model()
2023-08-25 05:16:44,511:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f8c64fd1250>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f8cb0c8ffd0>, model_only=True, return_train_score=False, kwargs={})
2023-08-25 05:16:44,511:INFO:Checking exceptions
2023-08-25 05:16:44,511:INFO:Importing libraries
2023-08-25 05:16:44,512:INFO:Copying training dataset
2023-08-25 05:16:44,545:INFO:Defining folds
2023-08-25 05:16:44,545:INFO:Declaring metric variables
2023-08-25 05:16:44,552:INFO:Importing untrained model
2023-08-25 05:16:44,564:INFO:Logistic Regression Imported successfully
2023-08-25 05:16:44,576:INFO:Starting cross validation
2023-08-25 05:16:44,579:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-25 05:16:53,907:INFO:Calculating mean and std
2023-08-25 05:16:53,918:INFO:Creating metrics dataframe
2023-08-25 05:16:53,929:INFO:Uploading results into container
2023-08-25 05:16:53,929:INFO:Uploading model into container now
2023-08-25 05:16:53,931:INFO:_master_model_container: 1
2023-08-25 05:16:53,931:INFO:_display_container: 2
2023-08-25 05:16:53,932:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=1754, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-08-25 05:16:53,932:INFO:create_model() successfully completed......................................
2023-08-25 05:16:54,165:INFO:SubProcess create_model() end ==================================
2023-08-25 05:16:54,165:INFO:Creating metrics dataframe
2023-08-25 05:16:54,176:INFO:Initializing K Neighbors Classifier
2023-08-25 05:16:54,176:INFO:Total runtime is 0.16120973428090413 minutes
2023-08-25 05:16:54,180:INFO:SubProcess create_model() called ==================================
2023-08-25 05:16:54,181:INFO:Initializing create_model()
2023-08-25 05:16:54,181:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f8c64fd1250>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f8cb0c8ffd0>, model_only=True, return_train_score=False, kwargs={})
2023-08-25 05:16:54,181:INFO:Checking exceptions
2023-08-25 05:16:54,181:INFO:Importing libraries
2023-08-25 05:16:54,181:INFO:Copying training dataset
2023-08-25 05:16:54,204:INFO:Defining folds
2023-08-25 05:16:54,205:INFO:Declaring metric variables
2023-08-25 05:16:54,209:INFO:Importing untrained model
2023-08-25 05:16:54,214:INFO:K Neighbors Classifier Imported successfully
2023-08-25 05:16:54,222:INFO:Starting cross validation
2023-08-25 05:16:54,223:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-25 05:17:35,629:INFO:Calculating mean and std
2023-08-25 05:17:35,673:INFO:Creating metrics dataframe
2023-08-25 05:17:35,703:INFO:Uploading results into container
2023-08-25 05:17:35,707:INFO:Uploading model into container now
2023-08-25 05:17:35,710:INFO:_master_model_container: 2
2023-08-25 05:17:35,710:INFO:_display_container: 2
2023-08-25 05:17:35,713:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-08-25 05:17:35,713:INFO:create_model() successfully completed......................................
2023-08-25 05:17:36,270:INFO:SubProcess create_model() end ==================================
2023-08-25 05:17:36,271:INFO:Creating metrics dataframe
2023-08-25 05:17:36,293:INFO:Initializing Naive Bayes
2023-08-25 05:17:36,293:INFO:Total runtime is 0.863156533241272 minutes
2023-08-25 05:17:36,298:INFO:SubProcess create_model() called ==================================
2023-08-25 05:17:36,299:INFO:Initializing create_model()
2023-08-25 05:17:36,299:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f8c64fd1250>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f8cb0c8ffd0>, model_only=True, return_train_score=False, kwargs={})
2023-08-25 05:17:36,299:INFO:Checking exceptions
2023-08-25 05:17:36,300:INFO:Importing libraries
2023-08-25 05:17:36,300:INFO:Copying training dataset
2023-08-25 05:17:36,329:INFO:Defining folds
2023-08-25 05:17:36,330:INFO:Declaring metric variables
2023-08-25 05:17:36,334:INFO:Importing untrained model
2023-08-25 05:17:36,340:INFO:Naive Bayes Imported successfully
2023-08-25 05:17:36,348:INFO:Starting cross validation
2023-08-25 05:17:36,349:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-25 05:17:36,992:INFO:Calculating mean and std
2023-08-25 05:17:36,994:INFO:Creating metrics dataframe
2023-08-25 05:17:37,000:INFO:Uploading results into container
2023-08-25 05:17:37,001:INFO:Uploading model into container now
2023-08-25 05:17:37,002:INFO:_master_model_container: 3
2023-08-25 05:17:37,002:INFO:_display_container: 2
2023-08-25 05:17:37,002:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-08-25 05:17:37,002:INFO:create_model() successfully completed......................................
2023-08-25 05:17:37,072:INFO:SubProcess create_model() end ==================================
2023-08-25 05:17:37,072:INFO:Creating metrics dataframe
2023-08-25 05:17:37,082:INFO:Initializing Decision Tree Classifier
2023-08-25 05:17:37,082:INFO:Total runtime is 0.8763150016466776 minutes
2023-08-25 05:17:37,086:INFO:SubProcess create_model() called ==================================
2023-08-25 05:17:37,086:INFO:Initializing create_model()
2023-08-25 05:17:37,087:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f8c64fd1250>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f8cb0c8ffd0>, model_only=True, return_train_score=False, kwargs={})
2023-08-25 05:17:37,087:INFO:Checking exceptions
2023-08-25 05:17:37,087:INFO:Importing libraries
2023-08-25 05:17:37,087:INFO:Copying training dataset
2023-08-25 05:17:37,119:INFO:Defining folds
2023-08-25 05:17:37,119:INFO:Declaring metric variables
2023-08-25 05:17:37,124:INFO:Importing untrained model
2023-08-25 05:17:37,129:INFO:Decision Tree Classifier Imported successfully
2023-08-25 05:17:37,137:INFO:Starting cross validation
2023-08-25 05:17:37,139:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-25 05:17:38,403:INFO:Calculating mean and std
2023-08-25 05:17:38,406:INFO:Creating metrics dataframe
2023-08-25 05:17:38,416:INFO:Uploading results into container
2023-08-25 05:17:38,417:INFO:Uploading model into container now
2023-08-25 05:17:38,418:INFO:_master_model_container: 4
2023-08-25 05:17:38,418:INFO:_display_container: 2
2023-08-25 05:17:38,418:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=1754, splitter='best')
2023-08-25 05:17:38,418:INFO:create_model() successfully completed......................................
2023-08-25 05:17:38,494:INFO:SubProcess create_model() end ==================================
2023-08-25 05:17:38,494:INFO:Creating metrics dataframe
2023-08-25 05:17:38,509:INFO:Initializing SVM - Linear Kernel
2023-08-25 05:17:38,509:INFO:Total runtime is 0.9000864624977112 minutes
2023-08-25 05:17:38,512:INFO:SubProcess create_model() called ==================================
2023-08-25 05:17:38,513:INFO:Initializing create_model()
2023-08-25 05:17:38,513:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f8c64fd1250>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f8cb0c8ffd0>, model_only=True, return_train_score=False, kwargs={})
2023-08-25 05:17:38,513:INFO:Checking exceptions
2023-08-25 05:17:38,513:INFO:Importing libraries
2023-08-25 05:17:38,514:INFO:Copying training dataset
2023-08-25 05:17:38,535:INFO:Defining folds
2023-08-25 05:17:38,535:INFO:Declaring metric variables
2023-08-25 05:17:38,540:INFO:Importing untrained model
2023-08-25 05:17:38,545:INFO:SVM - Linear Kernel Imported successfully
2023-08-25 05:17:38,552:INFO:Starting cross validation
2023-08-25 05:17:38,554:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-25 05:17:40,149:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-25 05:17:40,157:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-25 05:17:40,199:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-25 05:17:40,276:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-25 05:17:40,565:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-25 05:17:41,612:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-25 05:17:41,675:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-25 05:17:41,826:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-25 05:17:42,235:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-25 05:17:42,864:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-25 05:17:42,985:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-25 05:17:43,003:INFO:Calculating mean and std
2023-08-25 05:17:43,006:INFO:Creating metrics dataframe
2023-08-25 05:17:43,018:INFO:Uploading results into container
2023-08-25 05:17:43,018:INFO:Uploading model into container now
2023-08-25 05:17:43,019:INFO:_master_model_container: 5
2023-08-25 05:17:43,019:INFO:_display_container: 2
2023-08-25 05:17:43,019:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=1754, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-08-25 05:17:43,019:INFO:create_model() successfully completed......................................
2023-08-25 05:17:43,098:INFO:SubProcess create_model() end ==================================
2023-08-25 05:17:43,098:INFO:Creating metrics dataframe
2023-08-25 05:17:43,113:INFO:Initializing Ridge Classifier
2023-08-25 05:17:43,113:INFO:Total runtime is 0.9768285671869914 minutes
2023-08-25 05:17:43,118:INFO:SubProcess create_model() called ==================================
2023-08-25 05:17:43,118:INFO:Initializing create_model()
2023-08-25 05:17:43,119:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f8c64fd1250>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f8cb0c8ffd0>, model_only=True, return_train_score=False, kwargs={})
2023-08-25 05:17:43,119:INFO:Checking exceptions
2023-08-25 05:17:43,119:INFO:Importing libraries
2023-08-25 05:17:43,119:INFO:Copying training dataset
2023-08-25 05:17:43,145:INFO:Defining folds
2023-08-25 05:17:43,145:INFO:Declaring metric variables
2023-08-25 05:17:43,151:INFO:Importing untrained model
2023-08-25 05:17:43,161:INFO:Ridge Classifier Imported successfully
2023-08-25 05:17:43,174:INFO:Starting cross validation
2023-08-25 05:17:43,176:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-25 05:17:43,382:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_ridge.py:157: LinAlgWarning: Ill-conditioned matrix (rcond=1.95756e-19): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True, overwrite_a=True).T

2023-08-25 05:17:43,442:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-25 05:17:43,443:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_ridge.py:157: LinAlgWarning: Ill-conditioned matrix (rcond=1.9544e-19): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True, overwrite_a=True).T

2023-08-25 05:17:43,460:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_ridge.py:157: LinAlgWarning: Ill-conditioned matrix (rcond=1.95275e-19): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True, overwrite_a=True).T

2023-08-25 05:17:43,487:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-25 05:17:43,493:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_ridge.py:157: LinAlgWarning: Ill-conditioned matrix (rcond=1.95943e-19): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True, overwrite_a=True).T

2023-08-25 05:17:43,504:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-25 05:17:43,544:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-25 05:17:43,658:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_ridge.py:157: LinAlgWarning: Ill-conditioned matrix (rcond=1.95693e-19): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True, overwrite_a=True).T

2023-08-25 05:17:43,690:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_ridge.py:157: LinAlgWarning: Ill-conditioned matrix (rcond=1.95626e-19): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True, overwrite_a=True).T

2023-08-25 05:17:43,704:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-25 05:17:43,704:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_ridge.py:157: LinAlgWarning: Ill-conditioned matrix (rcond=1.95401e-19): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True, overwrite_a=True).T

2023-08-25 05:17:43,820:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_ridge.py:157: LinAlgWarning: Ill-conditioned matrix (rcond=1.9567e-19): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True, overwrite_a=True).T

2023-08-25 05:17:43,839:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-25 05:17:43,892:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-25 05:17:43,951:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-25 05:17:44,026:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_ridge.py:157: LinAlgWarning: Ill-conditioned matrix (rcond=1.95512e-19): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True, overwrite_a=True).T

2023-08-25 05:17:44,075:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-25 05:17:44,088:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_ridge.py:157: LinAlgWarning: Ill-conditioned matrix (rcond=1.9578e-19): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True, overwrite_a=True).T

2023-08-25 05:17:44,130:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/metrics.py", line 130, in _score
    return super()._score(
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-25 05:17:44,172:INFO:Calculating mean and std
2023-08-25 05:17:44,176:INFO:Creating metrics dataframe
2023-08-25 05:17:44,200:INFO:Uploading results into container
2023-08-25 05:17:44,203:INFO:Uploading model into container now
2023-08-25 05:17:44,205:INFO:_master_model_container: 6
2023-08-25 05:17:44,205:INFO:_display_container: 2
2023-08-25 05:17:44,205:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, normalize='deprecated', positive=False,
                random_state=1754, solver='auto', tol=0.001)
2023-08-25 05:17:44,206:INFO:create_model() successfully completed......................................
2023-08-25 05:17:44,311:INFO:SubProcess create_model() end ==================================
2023-08-25 05:17:44,311:INFO:Creating metrics dataframe
2023-08-25 05:17:44,328:INFO:Initializing Random Forest Classifier
2023-08-25 05:17:44,328:INFO:Total runtime is 0.9970723350842794 minutes
2023-08-25 05:17:44,338:INFO:SubProcess create_model() called ==================================
2023-08-25 05:17:44,338:INFO:Initializing create_model()
2023-08-25 05:17:44,338:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f8c64fd1250>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f8cb0c8ffd0>, model_only=True, return_train_score=False, kwargs={})
2023-08-25 05:17:44,339:INFO:Checking exceptions
2023-08-25 05:17:44,339:INFO:Importing libraries
2023-08-25 05:17:44,339:INFO:Copying training dataset
2023-08-25 05:17:44,374:INFO:Defining folds
2023-08-25 05:17:44,375:INFO:Declaring metric variables
2023-08-25 05:17:44,380:INFO:Importing untrained model
2023-08-25 05:17:44,389:INFO:Random Forest Classifier Imported successfully
2023-08-25 05:17:44,400:INFO:Starting cross validation
2023-08-25 05:17:44,402:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-25 05:17:58,797:INFO:Calculating mean and std
2023-08-25 05:17:58,798:INFO:Creating metrics dataframe
2023-08-25 05:17:58,811:INFO:Uploading results into container
2023-08-25 05:17:58,811:INFO:Uploading model into container now
2023-08-25 05:17:58,812:INFO:_master_model_container: 7
2023-08-25 05:17:58,812:INFO:_display_container: 2
2023-08-25 05:17:58,812:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=1754, verbose=0, warm_start=False)
2023-08-25 05:17:58,812:INFO:create_model() successfully completed......................................
2023-08-25 05:17:58,893:INFO:SubProcess create_model() end ==================================
2023-08-25 05:17:58,894:INFO:Creating metrics dataframe
2023-08-25 05:17:58,907:INFO:Initializing Quadratic Discriminant Analysis
2023-08-25 05:17:58,907:INFO:Total runtime is 1.2400553981463114 minutes
2023-08-25 05:17:58,910:INFO:SubProcess create_model() called ==================================
2023-08-25 05:17:58,911:INFO:Initializing create_model()
2023-08-25 05:17:58,911:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f8c64fd1250>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f8cb0c8ffd0>, model_only=True, return_train_score=False, kwargs={})
2023-08-25 05:17:58,911:INFO:Checking exceptions
2023-08-25 05:17:58,911:INFO:Importing libraries
2023-08-25 05:17:58,911:INFO:Copying training dataset
2023-08-25 05:17:58,932:INFO:Defining folds
2023-08-25 05:17:58,932:INFO:Declaring metric variables
2023-08-25 05:17:58,937:INFO:Importing untrained model
2023-08-25 05:17:58,942:INFO:Quadratic Discriminant Analysis Imported successfully
2023-08-25 05:17:58,950:INFO:Starting cross validation
2023-08-25 05:17:58,951:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-25 05:17:59,159:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/discriminant_analysis.py:878: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-08-25 05:17:59,159:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/discriminant_analysis.py:878: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-08-25 05:17:59,163:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/discriminant_analysis.py:878: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-08-25 05:17:59,166:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/discriminant_analysis.py:878: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-08-25 05:17:59,376:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/discriminant_analysis.py:878: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-08-25 05:17:59,398:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/discriminant_analysis.py:878: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-08-25 05:17:59,403:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/discriminant_analysis.py:878: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-08-25 05:17:59,412:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/discriminant_analysis.py:878: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-08-25 05:17:59,581:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/discriminant_analysis.py:878: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-08-25 05:17:59,586:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/sklearn/discriminant_analysis.py:878: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-08-25 05:17:59,662:INFO:Calculating mean and std
2023-08-25 05:17:59,664:INFO:Creating metrics dataframe
2023-08-25 05:17:59,680:INFO:Uploading results into container
2023-08-25 05:17:59,681:INFO:Uploading model into container now
2023-08-25 05:17:59,681:INFO:_master_model_container: 8
2023-08-25 05:17:59,681:INFO:_display_container: 2
2023-08-25 05:17:59,681:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-08-25 05:17:59,681:INFO:create_model() successfully completed......................................
2023-08-25 05:17:59,753:INFO:SubProcess create_model() end ==================================
2023-08-25 05:17:59,753:INFO:Creating metrics dataframe
2023-08-25 05:17:59,766:INFO:Initializing Ada Boost Classifier
2023-08-25 05:17:59,766:INFO:Total runtime is 1.2543725649515787 minutes
2023-08-25 05:17:59,769:INFO:SubProcess create_model() called ==================================
2023-08-25 05:17:59,770:INFO:Initializing create_model()
2023-08-25 05:17:59,770:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f8c64fd1250>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f8cb0c8ffd0>, model_only=True, return_train_score=False, kwargs={})
2023-08-25 05:17:59,770:INFO:Checking exceptions
2023-08-25 05:17:59,770:INFO:Importing libraries
2023-08-25 05:17:59,771:INFO:Copying training dataset
2023-08-25 05:17:59,791:INFO:Defining folds
2023-08-25 05:17:59,791:INFO:Declaring metric variables
2023-08-25 05:17:59,797:INFO:Importing untrained model
2023-08-25 05:17:59,802:INFO:Ada Boost Classifier Imported successfully
2023-08-25 05:17:59,811:INFO:Starting cross validation
2023-08-25 05:17:59,812:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-25 05:18:05,520:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py:260: UserWarning: Persisting input arguments took 0.53s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  fitted_estimator = self._memory_fit(

2023-08-25 05:18:07,817:INFO:Calculating mean and std
2023-08-25 05:18:07,819:INFO:Creating metrics dataframe
2023-08-25 05:18:07,843:INFO:Uploading results into container
2023-08-25 05:18:07,844:INFO:Uploading model into container now
2023-08-25 05:18:07,844:INFO:_master_model_container: 9
2023-08-25 05:18:07,844:INFO:_display_container: 2
2023-08-25 05:18:07,844:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=1754)
2023-08-25 05:18:07,845:INFO:create_model() successfully completed......................................
2023-08-25 05:18:07,918:INFO:SubProcess create_model() end ==================================
2023-08-25 05:18:07,918:INFO:Creating metrics dataframe
2023-08-25 05:18:07,931:INFO:Initializing Gradient Boosting Classifier
2023-08-25 05:18:07,931:INFO:Total runtime is 1.3904516299565632 minutes
2023-08-25 05:18:07,934:INFO:SubProcess create_model() called ==================================
2023-08-25 05:18:07,935:INFO:Initializing create_model()
2023-08-25 05:18:07,936:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f8c64fd1250>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f8cb0c8ffd0>, model_only=True, return_train_score=False, kwargs={})
2023-08-25 05:18:07,936:INFO:Checking exceptions
2023-08-25 05:18:07,936:INFO:Importing libraries
2023-08-25 05:18:07,936:INFO:Copying training dataset
2023-08-25 05:18:07,970:INFO:Defining folds
2023-08-25 05:18:07,970:INFO:Declaring metric variables
2023-08-25 05:18:07,982:INFO:Importing untrained model
2023-08-25 05:18:07,993:INFO:Gradient Boosting Classifier Imported successfully
2023-08-25 05:18:08,008:INFO:Starting cross validation
2023-08-25 05:18:08,010:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-25 05:18:28,592:INFO:Calculating mean and std
2023-08-25 05:18:28,594:INFO:Creating metrics dataframe
2023-08-25 05:18:28,617:INFO:Uploading results into container
2023-08-25 05:18:28,617:INFO:Uploading model into container now
2023-08-25 05:18:28,618:INFO:_master_model_container: 10
2023-08-25 05:18:28,618:INFO:_display_container: 2
2023-08-25 05:18:28,618:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=1754, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-08-25 05:18:28,619:INFO:create_model() successfully completed......................................
2023-08-25 05:18:28,691:INFO:SubProcess create_model() end ==================================
2023-08-25 05:18:28,692:INFO:Creating metrics dataframe
2023-08-25 05:18:28,707:INFO:Initializing Linear Discriminant Analysis
2023-08-25 05:18:28,708:INFO:Total runtime is 1.7367326180140177 minutes
2023-08-25 05:18:28,712:INFO:SubProcess create_model() called ==================================
2023-08-25 05:18:28,712:INFO:Initializing create_model()
2023-08-25 05:18:28,712:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f8c64fd1250>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f8cb0c8ffd0>, model_only=True, return_train_score=False, kwargs={})
2023-08-25 05:18:28,712:INFO:Checking exceptions
2023-08-25 05:18:28,713:INFO:Importing libraries
2023-08-25 05:18:28,713:INFO:Copying training dataset
2023-08-25 05:18:28,733:INFO:Defining folds
2023-08-25 05:18:28,733:INFO:Declaring metric variables
2023-08-25 05:18:28,738:INFO:Importing untrained model
2023-08-25 05:18:28,744:INFO:Linear Discriminant Analysis Imported successfully
2023-08-25 05:18:28,751:INFO:Starting cross validation
2023-08-25 05:18:28,752:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-25 05:18:29,907:INFO:Calculating mean and std
2023-08-25 05:18:29,909:INFO:Creating metrics dataframe
2023-08-25 05:18:29,958:INFO:Uploading results into container
2023-08-25 05:18:29,959:INFO:Uploading model into container now
2023-08-25 05:18:29,959:INFO:_master_model_container: 11
2023-08-25 05:18:29,959:INFO:_display_container: 2
2023-08-25 05:18:29,960:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-08-25 05:18:29,960:INFO:create_model() successfully completed......................................
2023-08-25 05:18:30,057:INFO:SubProcess create_model() end ==================================
2023-08-25 05:18:30,058:INFO:Creating metrics dataframe
2023-08-25 05:18:30,073:INFO:Initializing Extra Trees Classifier
2023-08-25 05:18:30,073:INFO:Total runtime is 1.7594917694727579 minutes
2023-08-25 05:18:30,078:INFO:SubProcess create_model() called ==================================
2023-08-25 05:18:30,079:INFO:Initializing create_model()
2023-08-25 05:18:30,079:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f8c64fd1250>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f8cb0c8ffd0>, model_only=True, return_train_score=False, kwargs={})
2023-08-25 05:18:30,079:INFO:Checking exceptions
2023-08-25 05:18:30,079:INFO:Importing libraries
2023-08-25 05:18:30,079:INFO:Copying training dataset
2023-08-25 05:18:30,113:INFO:Defining folds
2023-08-25 05:18:30,113:INFO:Declaring metric variables
2023-08-25 05:18:30,118:INFO:Importing untrained model
2023-08-25 05:18:30,128:INFO:Extra Trees Classifier Imported successfully
2023-08-25 05:18:30,141:INFO:Starting cross validation
2023-08-25 05:18:30,142:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-25 05:18:38,815:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py:260: UserWarning: Persisting input arguments took 0.75s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  fitted_estimator = self._memory_fit(

2023-08-25 05:18:40,207:WARNING:/Users/kendallherron/opt/anaconda3/lib/python3.9/site-packages/pycaret/internal/pipeline.py:260: UserWarning: Persisting input arguments took 0.52s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  fitted_estimator = self._memory_fit(

2023-08-25 05:18:43,903:INFO:Calculating mean and std
2023-08-25 05:18:43,908:INFO:Creating metrics dataframe
2023-08-25 05:18:43,952:INFO:Uploading results into container
2023-08-25 05:18:43,953:INFO:Uploading model into container now
2023-08-25 05:18:43,953:INFO:_master_model_container: 12
2023-08-25 05:18:43,953:INFO:_display_container: 2
2023-08-25 05:18:43,954:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=1754, verbose=0, warm_start=False)
2023-08-25 05:18:43,954:INFO:create_model() successfully completed......................................
2023-08-25 05:18:44,056:INFO:SubProcess create_model() end ==================================
2023-08-25 05:18:44,057:INFO:Creating metrics dataframe
2023-08-25 05:18:44,076:INFO:Initializing Light Gradient Boosting Machine
2023-08-25 05:18:44,076:INFO:Total runtime is 1.9928801854451497 minutes
2023-08-25 05:18:44,084:INFO:SubProcess create_model() called ==================================
2023-08-25 05:18:44,084:INFO:Initializing create_model()
2023-08-25 05:18:44,084:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f8c64fd1250>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f8cb0c8ffd0>, model_only=True, return_train_score=False, kwargs={})
2023-08-25 05:18:44,084:INFO:Checking exceptions
2023-08-25 05:18:44,085:INFO:Importing libraries
2023-08-25 05:18:44,085:INFO:Copying training dataset
2023-08-25 05:18:44,136:INFO:Defining folds
2023-08-25 05:18:44,136:INFO:Declaring metric variables
2023-08-25 05:18:44,146:INFO:Importing untrained model
2023-08-25 05:18:44,156:INFO:Light Gradient Boosting Machine Imported successfully
2023-08-25 05:18:44,170:INFO:Starting cross validation
2023-08-25 05:18:44,172:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-25 05:18:47,381:INFO:Calculating mean and std
2023-08-25 05:18:47,384:INFO:Creating metrics dataframe
2023-08-25 05:18:47,415:INFO:Uploading results into container
2023-08-25 05:18:47,416:INFO:Uploading model into container now
2023-08-25 05:18:47,416:INFO:_master_model_container: 13
2023-08-25 05:18:47,416:INFO:_display_container: 2
2023-08-25 05:18:47,417:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=1754, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
2023-08-25 05:18:47,417:INFO:create_model() successfully completed......................................
2023-08-25 05:18:47,488:INFO:SubProcess create_model() end ==================================
2023-08-25 05:18:47,488:INFO:Creating metrics dataframe
2023-08-25 05:18:47,503:INFO:Initializing Dummy Classifier
2023-08-25 05:18:47,503:INFO:Total runtime is 2.0499899347623187 minutes
2023-08-25 05:18:47,507:INFO:SubProcess create_model() called ==================================
2023-08-25 05:18:47,507:INFO:Initializing create_model()
2023-08-25 05:18:47,507:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f8c64fd1250>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f8cb0c8ffd0>, model_only=True, return_train_score=False, kwargs={})
2023-08-25 05:18:47,507:INFO:Checking exceptions
2023-08-25 05:18:47,507:INFO:Importing libraries
2023-08-25 05:18:47,507:INFO:Copying training dataset
2023-08-25 05:18:47,529:INFO:Defining folds
2023-08-25 05:18:47,530:INFO:Declaring metric variables
2023-08-25 05:18:47,536:INFO:Importing untrained model
2023-08-25 05:18:47,543:INFO:Dummy Classifier Imported successfully
2023-08-25 05:18:47,552:INFO:Starting cross validation
2023-08-25 05:18:47,553:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-25 05:18:48,295:INFO:Calculating mean and std
2023-08-25 05:18:48,296:INFO:Creating metrics dataframe
2023-08-25 05:18:48,349:INFO:Uploading results into container
2023-08-25 05:18:48,350:INFO:Uploading model into container now
2023-08-25 05:18:48,350:INFO:_master_model_container: 14
2023-08-25 05:18:48,350:INFO:_display_container: 2
2023-08-25 05:18:48,350:INFO:DummyClassifier(constant=None, random_state=1754, strategy='prior')
2023-08-25 05:18:48,350:INFO:create_model() successfully completed......................................
2023-08-25 05:18:48,437:INFO:SubProcess create_model() end ==================================
2023-08-25 05:18:48,437:INFO:Creating metrics dataframe
2023-08-25 05:18:48,469:INFO:Initializing create_model()
2023-08-25 05:18:48,469:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f8c64fd1250>, estimator=GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=1754, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, kwargs={})
2023-08-25 05:18:48,469:INFO:Checking exceptions
2023-08-25 05:18:48,474:INFO:Importing libraries
2023-08-25 05:18:48,475:INFO:Copying training dataset
2023-08-25 05:18:48,497:INFO:Defining folds
2023-08-25 05:18:48,497:INFO:Declaring metric variables
2023-08-25 05:18:48,497:INFO:Importing untrained model
2023-08-25 05:18:48,497:INFO:Declaring custom model
2023-08-25 05:18:48,498:INFO:Gradient Boosting Classifier Imported successfully
2023-08-25 05:18:48,499:INFO:Cross validation set to False
2023-08-25 05:18:48,499:INFO:Fitting Model
2023-08-25 05:18:53,176:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=1754, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-08-25 05:18:53,176:INFO:create_model() successfully completed......................................
2023-08-25 05:18:53,308:INFO:_master_model_container: 14
2023-08-25 05:18:53,308:INFO:_display_container: 2
2023-08-25 05:18:53,308:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=1754, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-08-25 05:18:53,308:INFO:compare_models() successfully completed......................................
2023-08-25 05:25:07,051:INFO:PyCaret ClassificationExperiment
2023-08-25 05:25:07,051:INFO:Logging name: clf-default-name
2023-08-25 05:25:07,051:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-08-25 05:25:07,051:INFO:version 3.0.4
2023-08-25 05:25:07,051:INFO:Initializing setup()
2023-08-25 05:25:07,051:INFO:self.USI: d390
2023-08-25 05:25:07,051:INFO:self._variable_keys: {'y_train', '_available_plots', 'idx', 'exp_id', 'fold_generator', 'exp_name_log', 'seed', 'USI', '_ml_usecase', 'html_param', 'data', 'log_plots_param', 'pipeline', 'fold_groups_param', 'n_jobs_param', 'is_multiclass', 'logging_param', 'X_train', 'gpu_param', 'gpu_n_jobs_param', 'X', 'X_test', 'y', 'fix_imbalance', 'target_param', 'y_test', 'memory', 'fold_shuffle_param'}
2023-08-25 05:25:07,051:INFO:Checking environment
2023-08-25 05:25:07,051:INFO:python_version: 3.9.12
2023-08-25 05:25:07,051:INFO:python_build: ('main', 'Apr  5 2022 01:53:17')
2023-08-25 05:25:07,051:INFO:machine: x86_64
2023-08-25 05:25:07,052:INFO:platform: macOS-10.16-x86_64-i386-64bit
2023-08-25 05:25:07,052:INFO:Memory: svmem(total=8589934592, available=2653159424, percent=69.1, used=4818747392, free=385089536, active=2273435648, inactive=2115371008, wired=2545311744)
2023-08-25 05:25:07,052:INFO:Physical Core: 2
2023-08-25 05:25:07,052:INFO:Logical Core: 4
2023-08-25 05:25:07,052:INFO:Checking libraries
2023-08-25 05:25:07,052:INFO:System:
2023-08-25 05:25:07,052:INFO:    python: 3.9.12 (main, Apr  5 2022, 01:53:17)  [Clang 12.0.0 ]
2023-08-25 05:25:07,052:INFO:executable: /Users/kendallherron/opt/anaconda3/bin/python
2023-08-25 05:25:07,052:INFO:   machine: macOS-10.16-x86_64-i386-64bit
2023-08-25 05:25:07,052:INFO:PyCaret required dependencies:
2023-08-25 05:25:07,052:INFO:                 pip: 21.2.4
2023-08-25 05:25:07,052:INFO:          setuptools: 61.2.0
2023-08-25 05:25:07,052:INFO:             pycaret: 3.0.4
2023-08-25 05:25:07,052:INFO:             IPython: 8.2.0
2023-08-25 05:25:07,052:INFO:          ipywidgets: 7.6.5
2023-08-25 05:25:07,053:INFO:                tqdm: 4.64.0
2023-08-25 05:25:07,054:INFO:               numpy: 1.21.5
2023-08-25 05:25:07,054:INFO:              pandas: 1.4.2
2023-08-25 05:25:07,054:INFO:              jinja2: 2.11.3
2023-08-25 05:25:07,054:INFO:               scipy: 1.7.3
2023-08-25 05:25:07,054:INFO:              joblib: 1.3.2
2023-08-25 05:25:07,054:INFO:             sklearn: 1.0.2
2023-08-25 05:25:07,054:INFO:                pyod: 1.1.0
2023-08-25 05:25:07,054:INFO:            imblearn: 0.11.0
2023-08-25 05:25:07,054:INFO:   category_encoders: 2.6.2
2023-08-25 05:25:07,054:INFO:            lightgbm: 3.3.2
2023-08-25 05:25:07,054:INFO:               numba: 0.55.1
2023-08-25 05:25:07,054:INFO:            requests: 2.27.1
2023-08-25 05:25:07,054:INFO:          matplotlib: 3.5.1
2023-08-25 05:25:07,054:INFO:          scikitplot: 0.3.7
2023-08-25 05:25:07,054:INFO:         yellowbrick: 1.5
2023-08-25 05:25:07,054:INFO:              plotly: 5.6.0
2023-08-25 05:25:07,054:INFO:    plotly-resampler: Not installed
2023-08-25 05:25:07,054:INFO:             kaleido: 0.2.1
2023-08-25 05:25:07,054:INFO:           schemdraw: 0.15
2023-08-25 05:25:07,054:INFO:         statsmodels: 0.13.2
2023-08-25 05:25:07,054:INFO:              sktime: 0.21.1
2023-08-25 05:25:07,054:INFO:               tbats: 1.1.3
2023-08-25 05:25:07,054:INFO:            pmdarima: 1.8.4
2023-08-25 05:25:07,054:INFO:              psutil: 5.9.5
2023-08-25 05:25:07,054:INFO:          markupsafe: 2.0.1
2023-08-25 05:25:07,054:INFO:             pickle5: Not installed
2023-08-25 05:25:07,055:INFO:         cloudpickle: 2.0.0
2023-08-25 05:25:07,055:INFO:         deprecation: 2.1.0
2023-08-25 05:25:07,055:INFO:              xxhash: 3.3.0
2023-08-25 05:25:07,055:INFO:           wurlitzer: 3.0.2
2023-08-25 05:25:07,055:INFO:PyCaret optional dependencies:
2023-08-25 05:25:07,055:INFO:                shap: Not installed
2023-08-25 05:25:07,055:INFO:           interpret: Not installed
2023-08-25 05:25:07,055:INFO:                umap: 0.5.3
2023-08-25 05:25:07,055:INFO:    pandas_profiling: 3.6.2
2023-08-25 05:25:07,055:INFO:  explainerdashboard: Not installed
2023-08-25 05:25:07,055:INFO:             autoviz: Not installed
2023-08-25 05:25:07,055:INFO:           fairlearn: Not installed
2023-08-25 05:25:07,055:INFO:          deepchecks: Not installed
2023-08-25 05:25:07,055:INFO:             xgboost: Not installed
2023-08-25 05:25:07,055:INFO:            catboost: Not installed
2023-08-25 05:25:07,055:INFO:              kmodes: Not installed
2023-08-25 05:25:07,055:INFO:             mlxtend: Not installed
2023-08-25 05:25:07,055:INFO:       statsforecast: Not installed
2023-08-25 05:25:07,055:INFO:        tune_sklearn: Not installed
2023-08-25 05:25:07,055:INFO:                 ray: Not installed
2023-08-25 05:25:07,055:INFO:            hyperopt: Not installed
2023-08-25 05:25:07,055:INFO:              optuna: Not installed
2023-08-25 05:25:07,055:INFO:               skopt: Not installed
2023-08-25 05:25:07,055:INFO:              mlflow: Not installed
2023-08-25 05:25:07,055:INFO:              gradio: Not installed
2023-08-25 05:25:07,055:INFO:             fastapi: Not installed
2023-08-25 05:25:07,055:INFO:             uvicorn: Not installed
2023-08-25 05:25:07,055:INFO:              m2cgen: Not installed
2023-08-25 05:25:07,056:INFO:           evidently: Not installed
2023-08-25 05:25:07,056:INFO:               fugue: Not installed
2023-08-25 05:25:07,056:INFO:           streamlit: Not installed
2023-08-25 05:25:07,056:INFO:             prophet: Not installed
2023-08-25 05:25:07,056:INFO:None
2023-08-25 05:25:07,056:INFO:Set up data.
2023-08-25 05:25:07,098:INFO:Set up train/test split.
2023-08-25 05:25:07,134:INFO:Set up index.
2023-08-25 05:25:07,135:INFO:Set up folding strategy.
2023-08-25 05:25:07,135:INFO:Assigning column types.
2023-08-25 05:25:07,142:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-08-25 05:25:07,192:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-08-25 05:25:07,193:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-25 05:25:07,224:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:25:07,224:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:25:07,276:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-08-25 05:25:07,277:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-25 05:25:07,309:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:25:07,309:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:25:07,310:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-08-25 05:25:07,365:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-25 05:25:07,405:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:25:07,405:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:25:07,465:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-25 05:25:07,503:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:25:07,503:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:25:07,503:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-08-25 05:25:07,595:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:25:07,595:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:25:07,681:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:25:07,682:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:25:07,683:INFO:Preparing preprocessing pipeline...
2023-08-25 05:25:07,684:INFO:Set up simple imputation.
2023-08-25 05:25:07,686:INFO:Set up column name cleaning.
2023-08-25 05:25:07,738:INFO:Finished creating preprocessing pipeline.
2023-08-25 05:25:07,744:INFO:Pipeline: Pipeline(memory=FastMemory(location=/var/folders/m3/xf6gvy7n3qdbcwzd5vjb0b7r0000gn/T/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['AcountNumber', 'CVV',
                                             'CustomerAge', 'Amount',
                                             'AverageIncomeExpendicture',
                                             'Gender_Female', 'Gender_Male',
                                             'MaritalStatus_Divorced',
                                             'MaritalStatus_Married',
                                             'MaritalStatus_Single',
                                             'MaritalStatus...
                                                              verbose=0))),
                ('categorical_imputer',
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose=0))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+')))],
         verbose=False)
2023-08-25 05:25:07,744:INFO:Creating final display dataframe.
2023-08-25 05:25:07,924:INFO:Setup _display_container:                     Description             Value
0                    Session id              2187
1                        Target           Outcome
2                   Target type            Binary
3           Original data shape       (37097, 27)
4        Transformed data shape       (37097, 27)
5   Transformed train set shape       (25967, 27)
6    Transformed test set shape       (11130, 27)
7              Numeric features                26
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                10
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              d390
2023-08-25 05:25:08,031:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:25:08,031:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:25:08,115:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:25:08,115:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-25 05:25:08,116:INFO:setup() successfully completed in 1.09s...............
